### ISSUE TITLE
"includes is not a function" error when running server.

### ISSUE THREAD

**Issue by joerobmunoz** [nordsimon/elasticsearch-graphql-server-example#2]
`TypeError: ["long","double","integer","float"].includes is not a function
    at C:\dev\tour-service\tour-query-service\node_modules\elasticsearch-graphql\lib\aggregations.js:51:48
    at Array.forEach (native)
    at convertFields (C:\dev\tour-service\tour-query-service\node_modules\elasticsearch-graphql\lib\aggregations.js:11:27)
    at aggregationsFromMapping (C:\dev\tour-service\tour-query-service\node_modules\elasticsearch-graphql\lib\aggregations.js:95:3)
    at module.exports (C:\dev\tour-service\tour-query-service\node_modules\elasticsearch-graphql\lib\schemaBuilder.js:8:14)
    at init (C:\dev\tour-service\tour-query-service\node_modules\elasticsearch-graphql\index.js:16:10)
    at Object.<anonymous> (C:\dev\tour-service\tour-query-service\server.js:44:26)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)`

It looks like the elasticsearch-graphql/lib/aggregations can only be run with harmony flags. Since "Includes" is not standard right now, we should update the package config run method to:

`
node --harmony_array_includes server.js
`

I can submit a PR if you'd like. Thanks for creating this example.

**Comment by nordsimon** [comment]
Hello

Well, my first answer would be to upgrade to node 6 since it moves in to LTS now. But the elasticsearch-graphql package is not very dependent of node 6 so i think i'll just remove `Array.includes` and patch with a legacy solution

**Comment by nordsimon** [comment]
Changed the elasticsearch-graphql packages now to utilize _.includes instead, so no need to put any harmony flags. Pull this repo and run `npm update` and you should be allright
